/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2020-07-20 at 06:48:21 UTC 
 * Modify at your own risk.
 */
package com.example.dailytasksamplepoc.kotlinomnicure.endpoints.loginEndpoints.model

import java.io.Serializable

class ChangePasswordRequest : Serializable {

    var email: String? = null


    var oldPassword: String? = null


    var newPassword: String? = null

    var confirmPassword: String? = null
}