/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2020-07-20 at 06:48:21 UTC 
 * Modify at your own risk.
 */
package com.example.dailytasksamplepoc.kotlinomnicure.endpoints.loginEndpoints.model

import java.io.Serializable


class Patient : Serializable {
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var acceptTime: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var address: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var appointmentId: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var arterialBloodPressureSystolic: Double? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var athenaDeviceId: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var bdProviderId: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var bdProviderName: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var bed: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var countryCode: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var dischargeMessage: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var dischargeTime: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var dob: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var dobDay: Int? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var dobMonth: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var dobYear: Int? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var docBoxManagerId: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var docBoxPatientId: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var email: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var fname: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var gender: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var heartRate: Double? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var hospital: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var hospitalId: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var id: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var inviteTime: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var joiningTime: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var lastMessageTime: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var lname: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var name: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var note: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var oxygenSupplement: Boolean? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var patientCondition: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var phone: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var picUrl: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var rdProviderId: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var rdProviderName: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var respiratoryRate: Double? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var score: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var spO2: Double? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var status: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var urgent: Boolean? = null
        private set

    /**
     * @param acceptTime acceptTime or `null` for none
     */
    fun setAcceptTime(acceptTime: Long?): Patient {
        this.acceptTime = acceptTime
        return this
    }

    /**
     * @param address address or `null` for none
     */
    fun setAddress(address: String?): Patient {
        this.address = address
        return this
    }

    /**
     * @param appointmentId appointmentId or `null` for none
     */
    fun setAppointmentId(appointmentId: Long?): Patient {
        this.appointmentId = appointmentId
        return this
    }

    /**
     * @param arterialBloodPressureSystolic arterialBloodPressureSystolic or `null` for none
     */
    fun setArterialBloodPressureSystolic(arterialBloodPressureSystolic: Double?): Patient {
        this.arterialBloodPressureSystolic = arterialBloodPressureSystolic
        return this
    }

    /**
     * @param athenaDeviceId athenaDeviceId or `null` for none
     */
    fun setAthenaDeviceId(athenaDeviceId: String?): Patient {
        this.athenaDeviceId = athenaDeviceId
        return this
    }

    /**
     * @param bdProviderId bdProviderId or `null` for none
     */
    fun setBdProviderId(bdProviderId: Long?): Patient {
        this.bdProviderId = bdProviderId
        return this
    }

    /**
     * @param bdProviderName bdProviderName or `null` for none
     */
    fun setBdProviderName(bdProviderName: String?): Patient {
        this.bdProviderName = bdProviderName
        return this
    }

    /**
     * @param bed bed or `null` for none
     */
    fun setBed(bed: String?): Patient {
        this.bed = bed
        return this
    }

    /**
     * @param countryCode countryCode or `null` for none
     */
    fun setCountryCode(countryCode: String?): Patient {
        this.countryCode = countryCode
        return this
    }

    /**
     * @param dischargeMessage dischargeMessage or `null` for none
     */
    fun setDischargeMessage(dischargeMessage: String?): Patient {
        this.dischargeMessage = dischargeMessage
        return this
    }

    /**
     * @param dischargeTime dischargeTime or `null` for none
     */
    fun setDischargeTime(dischargeTime: Long?): Patient {
        this.dischargeTime = dischargeTime
        return this
    }

    /**
     * @param dob dob or `null` for none
     */
    fun setDob(dob: Long?): Patient {
        this.dob = dob
        return this
    }

    /**
     * @param dobDay dobDay or `null` for none
     */
    fun setDobDay(dobDay: Int?): Patient {
        this.dobDay = dobDay
        return this
    }

    /**
     * @param dobMonth dobMonth or `null` for none
     */
    fun setDobMonth(dobMonth: String?): Patient {
        this.dobMonth = dobMonth
        return this
    }

    /**
     * @param dobYear dobYear or `null` for none
     */
    fun setDobYear(dobYear: Int?): Patient {
        this.dobYear = dobYear
        return this
    }

    /**
     * @param docBoxManagerId docBoxManagerId or `null` for none
     */
    fun setDocBoxManagerId(docBoxManagerId: String?): Patient {
        this.docBoxManagerId = docBoxManagerId
        return this
    }

    /**
     * @param docBoxPatientId docBoxPatientId or `null` for none
     */
    fun setDocBoxPatientId(docBoxPatientId: String?): Patient {
        this.docBoxPatientId = docBoxPatientId
        return this
    }

    /**
     * @param email email or `null` for none
     */
    fun setEmail(email: String?): Patient {
        this.email = email
        return this
    }

    /**
     * @param fname fname or `null` for none
     */
    fun setFname(fname: String?): Patient {
        this.fname = fname
        return this
    }

    /**
     * @param gender gender or `null` for none
     */
    fun setGender(gender: String?): Patient {
        this.gender = gender
        return this
    }

    /**
     * @param heartRate heartRate or `null` for none
     */
    fun setHeartRate(heartRate: Double?): Patient {
        this.heartRate = heartRate
        return this
    }

    /**
     * @param hospital hospital or `null` for none
     */
    fun setHospital(hospital: String?): Patient {
        this.hospital = hospital
        return this
    }

    /**
     * @param hospitalId hospitalId or `null` for none
     */
    fun setHospitalId(hospitalId: Long?): Patient {
        this.hospitalId = hospitalId
        return this
    }

    /**
     * @param id id or `null` for none
     */
    fun setId(id: Long?): Patient {
        this.id = id
        return this
    }

    /**
     * @param inviteTime inviteTime or `null` for none
     */
    fun setInviteTime(inviteTime: Long?): Patient {
        this.inviteTime = inviteTime
        return this
    }

    /**
     * @param joiningTime joiningTime or `null` for none
     */
    fun setJoiningTime(joiningTime: Long?): Patient {
        this.joiningTime = joiningTime
        return this
    }

    /**
     * @param lastMessageTime lastMessageTime or `null` for none
     */
    fun setLastMessageTime(lastMessageTime: Long?): Patient {
        this.lastMessageTime = lastMessageTime
        return this
    }

    /**
     * @param lname lname or `null` for none
     */
    fun setLname(lname: String?): Patient {
        this.lname = lname
        return this
    }

    /**
     * @param name name or `null` for none
     */
    fun setName(name: String?): Patient {
        this.name = name
        return this
    }

    /**
     * @param note note or `null` for none
     */
    fun setNote(note: String?): Patient {
        this.note = note
        return this
    }

    /**
     * @param oxygenSupplement oxygenSupplement or `null` for none
     */
    fun setOxygenSupplement(oxygenSupplement: Boolean?): Patient {
        this.oxygenSupplement = oxygenSupplement
        return this
    }

    /**
     * @param patientCondition patientCondition or `null` for none
     */
    fun setPatientCondition(patientCondition: String?): Patient {
        this.patientCondition = patientCondition
        return this
    }

    /**
     * @param phone phone or `null` for none
     */
    fun setPhone(phone: String?): Patient {
        this.phone = phone
        return this
    }

    /**
     * @param picUrl picUrl or `null` for none
     */
    fun setPicUrl(picUrl: String?): Patient {
        this.picUrl = picUrl
        return this
    }

    /**
     * @param rdProviderId rdProviderId or `null` for none
     */
    fun setRdProviderId(rdProviderId: Long?): Patient {
        this.rdProviderId = rdProviderId
        return this
    }

    /**
     * @param rdProviderName rdProviderName or `null` for none
     */
    fun setRdProviderName(rdProviderName: String?): Patient {
        this.rdProviderName = rdProviderName
        return this
    }

    /**
     * @param respiratoryRate respiratoryRate or `null` for none
     */
    fun setRespiratoryRate(respiratoryRate: Double?): Patient {
        this.respiratoryRate = respiratoryRate
        return this
    }

    /**
     * @param score score or `null` for none
     */
    fun setScore(score: String?): Patient {
        this.score = score
        return this
    }

    /**
     * @param spO2 spO2 or `null` for none
     */
    fun setSpO2(spO2: Double?): Patient {
        this.spO2 = spO2
        return this
    }

    /**
     * @param status status or `null` for none
     */
    fun setStatus(status: String?): Patient {
        this.status = status
        return this
    }

    /**
     * @param urgent urgent or `null` for none
     */
    fun setUrgent(urgent: Boolean?): Patient {
        this.urgent = urgent
        return this
    } //  @Override
    //  public Patient set(String fieldName, Object value) {
    //    return (Patient) super.set(fieldName, value);
    //  }
    //
    //  @Override
    //  public Patient clone() {
    //    return (Patient) super.clone();
    //  }
}