/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2020-07-20 at 06:48:21 UTC 
 * Modify at your own risk.
 */
package com.example.dailytasksamplepoc.kotlinomnicure.endpoints.loginEndpoints.model

import java.io.Serializable


class Role : Serializable {
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var accessType: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var id: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var providerId: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var roleType: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key @com.google.api.client.json.JsonString
    var time: Long? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var typeId: String? = null
        private set
    /**
     * @return value or `null` for none
     */
    /**
     * The value may be `null`.
     */
    //com.google.api.client.util.Key
    var typeName: String? = null
        private set

    /**
     * @param accessType accessType or `null` for none
     */
    fun setAccessType(accessType: String?): Role {
        this.accessType = accessType
        return this
    }

    /**
     * @param id id or `null` for none
     */
    fun setId(id: Long?): Role {
        this.id = id
        return this
    }

    /**
     * @param providerId providerId or `null` for none
     */
    fun setProviderId(providerId: Long?): Role {
        this.providerId = providerId
        return this
    }

    /**
     * @param roleType roleType or `null` for none
     */
    fun setRoleType(roleType: String?): Role {
        this.roleType = roleType
        return this
    }

    /**
     * @param time time or `null` for none
     */
    fun setTime(time: Long?): Role {
        this.time = time
        return this
    }

    /**
     * @param typeId typeId or `null` for none
     */
    fun setTypeId(typeId: String?): Role {
        this.typeId = typeId
        return this
    }

    /**
     * @param typeName typeName or `null` for none
     */
    fun setTypeName(typeName: String?): Role {
        this.typeName = typeName
        return this
    } //  @Override
    //  public Role set(String fieldName, Object value) {
    //    return (Role) super.set(fieldName, value);
    //  }
    //
    //  @Override
    //  public Role clone() {
    //    return (Role) super.clone();
    //  }
}